package heartbeat

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"time"

	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/runkit/internal/x/xsql"
)

const (
	// Interval is the time between heartbeats.
	Interval = 100 * time.Millisecond

	// Tolerance is the number of missed heartbeat intervals before considering
	// a node unhealthy.
	Tolerance = 3
)

// Writer periodically writes heartbeat records to the database.
type Writer struct {
	// NodeID is the UUID of this node. It is used as the keyspace key.
	NodeID *uuidpb.UUID

	// DB is the database connection used to write heartbeat records.
	DB *sql.DB

	// Logger is the target for log messages generated by the heartbeat writer.
	Logger *slog.Logger
}

// Run writes an initial heartbeat record and refreshes it on every interval
// tick until ctx is cancelled, at which point the record is deleted.
func (w *Writer) Run(ctx context.Context) error {
	inserted := false

	for {
		refreshAt := time.Now().Add(Interval)
		expiresAt := refreshAt.Add(Tolerance * Interval)

		var (
			ok  bool
			err error
		)

		if inserted {
			ok, err = w.update(ctx, expiresAt)
		} else {
			ok, err = w.insert(ctx, expiresAt)
		}

		if err != nil {
			w.Logger.Error(
				"unable to write heartbeat record",
				slog.String("error", err.Error()),
			)
		} else if !ok {
			return fmt.Errorf(
				"unable to write heartbeat record: node ID %s conflicts with another node",
				w.NodeID,
			)
		} else {
			inserted = true
		}

		select {
		case <-time.After(time.Until(refreshAt)):
			continue
		case <-ctx.Done():
			if inserted {
				w.delete()
			}
			return ctx.Err()
		}
	}
}

func (w *Writer) insert(ctx context.Context, expiresAt time.Time) (bool, error) {
	res, err := w.DB.ExecContext(
		ctx,
		`INSERT INTO cluster.heartbeats (
			node_id,
			expires_at
		)
		VALUES ($1, $2)
		ON CONFLICT (node_id) DO NOTHING`,
		xsql.UUID(w.NodeID),
		expiresAt,
	)
	if err != nil {
		return false, err
	}

	n, err := res.RowsAffected()
	if err != nil {
		return false, err
	}

	return n == 1, nil
}

func (w *Writer) update(ctx context.Context, expiresAt time.Time) (bool, error) {
	res, err := w.DB.ExecContext(
		ctx,
		`UPDATE cluster.heartbeats
		SET expires_at = $2
		WHERE node_id = $1`,
		xsql.UUID(w.NodeID),
		expiresAt,
	)
	if err != nil {
		return false, err
	}

	n, err := res.RowsAffected()
	if err != nil {
		return false, err
	}

	return n == 1, nil
}

func (w *Writer) delete() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if _, err := w.DB.ExecContext(
		ctx,
		`DELETE FROM cluster.heartbeats
		WHERE node_id = $1`,
		xsql.UUID(w.NodeID),
	); err != nil {
		w.Logger.Error("unable to remove heartbeat record", "error", err)
	}
}
