package heartbeat

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/runkit/internal/x/xslog"
	"github.com/dogmatiq/runkit/internal/x/xsql"
)

// Observer monitors the heartbeat table and sends notifications when the set of
// live nodes changes.
type Observer struct {
	// DB is the database connection used to read heartbeat records.
	DB *sql.DB

	// Logger is the target for log messages generated by the observer.
	Logger *slog.Logger

	m     sync.Mutex
	nodes *uuidpb.Set
	subs  map[chan<- *uuidpb.Set]bool
}

// Run polls the heartbeat table until ctx is canceled, sending notifications of
// each change to the set of live nodes.
func (o *Observer) Run(ctx context.Context) {
	ticker := time.NewTicker(Interval)
	defer ticker.Stop()

	for {
		if err := o.poll(ctx); err != nil {
			if ctx.Err() != nil {
				return
			}

			o.Logger.ErrorContext(
				ctx,
				"unable to read live cluster members",
				xslog.Error(err),
			)
		}

		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
		}
	}
}

// Subscribe registers ch to receive changes to the live nodes in the cluster, and
// returns a func that unsubscribes.
func (o *Observer) Subscribe(ch chan<- *uuidpb.Set) func() {
	o.m.Lock()
	defer o.m.Unlock()

	if o.subs == nil {
		o.subs = map[chan<- *uuidpb.Set]bool{}
	}

	o.subs[ch] = true

	var once sync.Once

	return func() {
		once.Do(func() {
			o.m.Lock()
			defer o.m.Unlock()
			delete(o.subs, ch)
		})
	}
}

// poll reads the current set of live nodes and notifies all subscribers if it
// has changed.
func (o *Observer) poll(ctx context.Context) error {
	nodes, err := o.read(ctx)
	if err != nil {
		return err
	}

	hasChanged := !nodes.IsEqual(o.nodes)
	if hasChanged {
		o.nodes = nodes
	}

	var sends sync.WaitGroup

	func() {
		o.m.Lock()
		defer o.m.Unlock()

		for ch, isNew := range o.subs {
			if isNew {
				o.subs[ch] = false

				if nodes.Len() == 0 {
					continue
				}
			} else if !hasChanged {
				continue
			}

			sends.Go(func() {
				select {
				case ch <- nodes:
				case <-ctx.Done():
				}
			})
		}
	}()

	sends.Wait()

	return ctx.Err()
}

// read returns the set of nodes whose heartbeat records have not expired.
func (o *Observer) read(ctx context.Context) (*uuidpb.Set, error) {
	rows, err := o.DB.QueryContext(
		ctx,
		`SELECT node_id
		FROM cluster.heartbeats
		WHERE expires_at > clock_timestamp()`,
	)
	if err != nil {
		return nil, fmt.Errorf("unable to query live nodes: %w", err)
	}
	defer rows.Close()

	live := &uuidpb.Set{}

	for rows.Next() {
		id := &uuidpb.UUID{}
		if err := rows.Scan(xsql.UUID(id)); err != nil {
			return nil, fmt.Errorf("unable to scan node ID: %w", err)
		}

		live.Add(id)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("unable to iterate live nodes: %w", err)
	}

	return live, nil
}
