package heartbeat

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/runkit/internal/x/xslog"
	"github.com/dogmatiq/runkit/internal/x/xsql"
)

// Reader monitors the heartbeat table and notifies observers when the set of
// live nodes in the cluster changes.
type Reader struct {
	// DB is the database connection used to read heartbeat records.
	DB *sql.DB

	// Logger is the target for log messages generated by the reader.
	Logger *slog.Logger

	m         sync.Mutex
	nodes     *uuidpb.Set
	observers map[chan<- *uuidpb.Set]bool
}

// Run polls the heartbeat table until ctx is canceled, notifying observers of
// each change to the set of live nodes.
func (r *Reader) Run(ctx context.Context) {
	ticker := time.NewTicker(Interval)
	defer ticker.Stop()

	for {
		if err := r.poll(ctx); err != nil {
			if ctx.Err() != nil {
				return
			}

			r.Logger.ErrorContext(
				ctx,
				"unable to read live cluster members",
				xslog.Error(err),
			)
		}

		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
		}
	}
}

// Observe registers ch to receive changes to the live nodes in the cluster, and
// returns a func that stops observing.
//
// It returns a func that can be called to stop observing changes.
func (r *Reader) Observe(ch chan<- *uuidpb.Set) func() {
	r.m.Lock()
	defer r.m.Unlock()

	if r.observers == nil {
		r.observers = map[chan<- *uuidpb.Set]bool{}
	}

	r.observers[ch] = true

	var once sync.Once

	return func() {
		once.Do(func() {
			r.m.Lock()
			defer r.m.Unlock()
			delete(r.observers, ch)
		})
	}
}

// poll reads the current set of live nodes and notifies observers if it has
// changed.
func (r *Reader) poll(ctx context.Context) error {
	nodes, err := r.read(ctx)
	if err != nil {
		return err
	}

	hasChanged := !nodes.IsEqual(r.nodes)
	if hasChanged {
		r.nodes = nodes
	}

	var sends sync.WaitGroup

	func() {
		r.m.Lock()
		defer r.m.Unlock()

		for ch, isNew := range r.observers {
			if isNew {
				r.observers[ch] = false

				if nodes.Len() == 0 {
					continue
				}
			} else if !hasChanged {
				continue
			}

			sends.Go(func() {
				select {
				case ch <- nodes:
				case <-ctx.Done():
				}
			})
		}
	}()

	sends.Wait()

	return ctx.Err()
}

// read returns the set of nodes whose heartbeat records have not expired.
func (r *Reader) read(ctx context.Context) (*uuidpb.Set, error) {
	rows, err := r.DB.QueryContext(
		ctx,
		`SELECT node_id
		FROM cluster.heartbeats
		WHERE expires_at > clock_timestamp()`,
	)
	if err != nil {
		return nil, fmt.Errorf("unable to query live nodes: %w", err)
	}
	defer rows.Close()

	live := &uuidpb.Set{}

	for rows.Next() {
		id := &uuidpb.UUID{}
		if err := rows.Scan(xsql.UUID(id)); err != nil {
			return nil, fmt.Errorf("unable to scan node ID: %w", err)
		}

		live.Add(id)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("unable to iterate live nodes: %w", err)
	}

	return live, nil
}
