package heartbeat

import (
	"context"
	"database/sql"
	"log/slog"
	"time"

	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/runkit/internal/x/xsql"
)

const (
	// Interval is the time between heartbeats.
	Interval = 100 * time.Millisecond

	// Tolerance is the number of missed heartbeat intervals before considering
	// a node unhealthy.
	Tolerance = 3
)

// Writer periodically writes heartbeat records to the database.
type Writer struct {
	// NodeID is the UUID of this node. It is used as the keyspace key.
	NodeID *uuidpb.UUID

	// DB is the database connection used to write heartbeat records.
	DB *sql.DB

	// Logger is the target for log messages generated by the heartbeat writer.
	Logger *slog.Logger
}

// Run writes an initial heartbeat record and refreshes it on every interval
// tick until ctx is cancelled, at which point the record is deleted.
func (w *Writer) Run(ctx context.Context) {
	for {
		refreshAt := time.Now().Add(Interval)
		expiresAt := refreshAt.Add(Tolerance * Interval)

		if _, err := w.DB.ExecContext(
			ctx,
			`INSERT INTO cluster.heartbeats (
				node_id,
				expires_at
			)
			VALUES ($1, $2)
			ON CONFLICT (node_id) DO UPDATE SET
				expires_at = EXCLUDED.expires_at`,
			xsql.UUID(w.NodeID),
			expiresAt,
		); err != nil {
			if err == ctx.Err() {
				return
			}

			w.Logger.ErrorContext(
				ctx,
				"unable to write heartbeat record",
				slog.String("error", err.Error()),
			)
		}

		select {
		case <-time.After(time.Until(refreshAt)):
			continue
		case <-ctx.Done():
			w.delete()
			return
		}
	}
}

func (w *Writer) delete() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if _, err := w.DB.ExecContext(
		ctx,
		`DELETE FROM cluster.heartbeats
		WHERE node_id = $1`,
		xsql.UUID(w.NodeID),
	); err != nil {
		w.Logger.Error("unable to remove heartbeat record", "error", err)
	}
}
