package heartbeat

import (
	"context"
	"database/sql"
	"log/slog"
	"time"

	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/runkit/internal/x/xsql"
)

const (
	// Interval is the time between heartbeats.
	Interval = 100 * time.Millisecond

	// Tolerance is the number of missed heartbeat intervals before considering
	// a node unhealthy.
	Tolerance = 3
)

// Writer periodically writes heartbeat records to the database.
type Writer struct {
	// NodeID is the UUID of this node. It is used as the keyspace key.
	NodeID *uuidpb.UUID

	// DB is the database connection used to write heartbeat records.
	DB *sql.DB

	// Logger is the target for log messages generated by the heartbeat writer.
	Logger *slog.Logger
}

// Run writes an initial heartbeat record and refreshes it on every interval
// tick until ctx is cancelled, at which point the record is deleted.
func (w *Writer) Run(ctx context.Context) {
	w.purge(ctx)
	defer w.delete()

	for {
		refreshAt := time.Now().Add(Interval)
		w.update(ctx, refreshAt)
		delay := time.Until(refreshAt)

		select {
		case <-ctx.Done():
			return
		case <-time.After(delay):
		}
	}
}

// update writes the heartbeat record for this node.
func (w *Writer) update(ctx context.Context, refreshAt time.Time) {
	expiresAt := refreshAt.Add(Tolerance * Interval)

	if _, err := w.DB.ExecContext(
		ctx,
		`INSERT INTO cluster.heartbeats (
			node_id,
			expires_at
		)
		VALUES ($1, $2)
		ON CONFLICT (node_id) DO UPDATE SET
			expires_at = EXCLUDED.expires_at`,
		xsql.UUID(w.NodeID),
		expiresAt,
	); err != nil {
		if err != ctx.Err() {
			w.Logger.ErrorContext(
				ctx,
				"unable to write heartbeat record",
				slog.String("error", err.Error()),
			)
		}
	}
}

// delete removes the heartbeat record for this node from the database.
func (w *Writer) delete() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if _, err := w.DB.ExecContext(
		ctx,
		`DELETE FROM cluster.heartbeats
		WHERE node_id = $1`,
		xsql.UUID(w.NodeID),
	); err != nil {
		w.Logger.Error("unable to remove heartbeat record", "error", err)
	}
}

// purge removes all expired heartbeat records from the database.
func (w *Writer) purge(ctx context.Context) {
	if _, err := w.DB.ExecContext(
		ctx,
		`DELETE FROM cluster.heartbeats
		WHERE expires_at <= clock_timestamp()`,
	); err != nil {
		w.Logger.ErrorContext(
			ctx,
			"unable to delete expired heartbeat records",
			slog.String("error", err.Error()),
		)
	}
}
