package cluster

import (
	"context"
	"database/sql"
	"log/slog"
	"time"

	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/runkit/internal/x/xsql"
)

const (
	// HeartbeatInterval is the time between heartbeats.
	HeartbeatInterval = 100 * time.Millisecond

	// HeartbeatTimeout is the amount of time a node can go without sending a
	// heartbeat before it is considered offline.
	HeartbeatTimeout = 3 * HeartbeatInterval
)

// Heartbeater periodically sends heartbeat notifications to other
// nodes within the cluster.
type Heartbeater struct {
	// NodeID is the UUID of this node. It is used as the keyspace key.
	NodeID *uuidpb.UUID

	// DB is the database connection used to write heartbeat records.
	DB *sql.DB

	// Logger is the target for log messages generated by the heart.
	Logger *slog.Logger
}

// Run writes an initial heartbeat record and refreshes it on every interval
// tick until ctx is cancelled, at which point the record is deleted.
func (h *Heartbeater) Run(ctx context.Context) {
	ticker := time.NewTicker(HeartbeatInterval)
	defer ticker.Stop()

	for {
		if _, err := h.DB.ExecContext(
			ctx,
			`SELECT pg_notify('heartbeat', $1)`,
			xsql.UUID(h.NodeID),
		); err != nil {
			if ctx.Err() != nil {
				return
			}

			h.Logger.ErrorContext(
				ctx,
				"unable to send heartbeat notification",
				slog.String("error", err.Error()),
			)
		}

		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
		}
	}
}
