syntax = "proto3";
package runkit.eventstream.journal.v1;

option go_package = "github.com/dogmatiq/runkit/internal/eventstream/internal/eventstreamjournal";

import "github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto";

// Record is an entry in the journal.
message Record {
  // OffsetBefore is the highest stream offset before this record was appended.
  uint64 offset_before = 1;

  // OffsetAfter is the highest stream offset after this record was appended.
  uint64 offset_after = 2;

  // Op is the operation being performed.
  oneof op { AppendEvents append_events = 3; }
}

// AppendEvents is an operation that appends events to the stream.
message AppendEvents {
  // Events is the ordered list of envelopes containing the appended events.
  repeated dogma.protobuf.Envelope events = 1;
}
