// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: github.com/dogmatiq/runkit/internal/eventstream/internal/eventstreamjournal/record.proto

package eventstreamjournal

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Record is an entry in the journal.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OffsetBefore is the highest stream offset before this record was appended.
	OffsetBefore uint64 `protobuf:"varint,1,opt,name=offset_before,json=offsetBefore,proto3" json:"offset_before,omitempty"`
	// OffsetAfter is the highest stream offset after this record was appended.
	OffsetAfter uint64 `protobuf:"varint,2,opt,name=offset_after,json=offsetAfter,proto3" json:"offset_after,omitempty"`
	// Op is the operation being performed.
	//
	// Types that are valid to be assigned to Op:
	//
	//	*Record_AppendEvents
	Op            isRecord_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetOffsetBefore() uint64 {
	if x != nil {
		return x.OffsetBefore
	}
	return 0
}

func (x *Record) GetOffsetAfter() uint64 {
	if x != nil {
		return x.OffsetAfter
	}
	return 0
}

func (x *Record) GetOp() isRecord_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Record) GetAppendEvents() *AppendEvents {
	if x != nil {
		if x, ok := x.Op.(*Record_AppendEvents); ok {
			return x.AppendEvents
		}
	}
	return nil
}

type isRecord_Op interface {
	isRecord_Op()
}

type Record_AppendEvents struct {
	AppendEvents *AppendEvents `protobuf:"bytes,3,opt,name=append_events,json=appendEvents,proto3,oneof"`
}

func (*Record_AppendEvents) isRecord_Op() {}

// AppendEvents is an operation that appends events to the stream.
type AppendEvents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events is the ordered list of envelopes containing the appended events.
	Events        []*envelopepb.Envelope `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEvents) Reset() {
	*x = AppendEvents{}
	mi := &file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEvents) ProtoMessage() {}

func (x *AppendEvents) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEvents.ProtoReflect.Descriptor instead.
func (*AppendEvents) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEvents) GetEvents() []*envelopepb.Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDesc = "" +
	"\n" +
	"Xgithub.com/dogmatiq/runkit/internal/eventstream/internal/eventstreamjournal/record.proto\x12\x1drunkit.eventstream.journal.v1\x1a@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\"\xaa\x01\n" +
	"\x06Record\x12#\n" +
	"\roffset_before\x18\x01 \x01(\x04R\foffsetBefore\x12!\n" +
	"\foffset_after\x18\x02 \x01(\x04R\voffsetAfter\x12R\n" +
	"\rappend_events\x18\x03 \x01(\v2+.runkit.eventstream.journal.v1.AppendEventsH\x00R\fappendEventsB\x04\n" +
	"\x02op\"@\n" +
	"\fAppendEvents\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.dogma.protobuf.EnvelopeR\x06eventsBMZKgithub.com/dogmatiq/runkit/internal/eventstream/internal/eventstreamjournalb\x06proto3"

var (
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescData []byte
)

func file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDescData
}

var file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_goTypes = []any{
	(*Record)(nil),              // 0: runkit.eventstream.journal.v1.Record
	(*AppendEvents)(nil),        // 1: runkit.eventstream.journal.v1.AppendEvents
	(*envelopepb.Envelope)(nil), // 2: dogma.protobuf.Envelope
}
var file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_depIdxs = []int32{
	1, // 0: runkit.eventstream.journal.v1.Record.append_events:type_name -> runkit.eventstream.journal.v1.AppendEvents
	2, // 1: runkit.eventstream.journal.v1.AppendEvents.events:type_name -> dogma.protobuf.Envelope
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_init()
}
func file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_init() {
	if File_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto != nil {
		return
	}
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes[0].OneofWrappers = []any{
		(*Record_AppendEvents)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto = out.File
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_goTypes = nil
	file_github_com_dogmatiq_runkit_internal_eventstream_internal_eventstreamjournal_record_proto_depIdxs = nil
}
