// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/runkit/internal/eventstream/internal/eventstreamjournal/record.proto

package eventstreamjournal

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	proto "google.golang.org/protobuf/proto"
)

// TryGetAppendEvents returns x.Op.AppendEvents if x.Op is a [Record_AppendEvents].
// Otherwise, ok is false and v is the zero-value.
func (x *Record) TryGetAppendEvents() (v *AppendEvents, ok bool) {
	if x, ok := x.GetOp().(*Record_AppendEvents); ok {
		return x.AppendEvents, true
	}
	return v, false
}

type RecordBuilder struct {
	prototype Record
}

// NewRecordBuilder returns a builder that constructs [Record] messages.
func NewRecordBuilder() *RecordBuilder {
	return &RecordBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *RecordBuilder) From(x *Record) *RecordBuilder {
	b.prototype.OffsetBefore = x.OffsetBefore
	b.prototype.OffsetAfter = x.OffsetAfter
	b.prototype.Op = x.Op
	return b
}

// Build returns a new [Record] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *RecordBuilder) Build() *Record {
	return &Record{
		OffsetBefore: b.prototype.OffsetBefore,
		OffsetAfter:  b.prototype.OffsetAfter,
		Op:           b.prototype.Op,
	}
}

// WithOffsetBefore configures the builder to set the OffsetBefore field to v,
// then returns b.
func (b *RecordBuilder) WithOffsetBefore(v uint64) *RecordBuilder {
	b.prototype.OffsetBefore = v
	return b
}

// WithOffsetAfter configures the builder to set the OffsetAfter field to v,
// then returns b.
func (b *RecordBuilder) WithOffsetAfter(v uint64) *RecordBuilder {
	b.prototype.OffsetAfter = v
	return b
}

// WithAppendEvents configures the builder to set the Op field to a
// [Record_AppendEvents] value containing v, then returns b
func (b *RecordBuilder) WithAppendEvents(v *AppendEvents) *RecordBuilder {
	b.prototype.Op = &Record_AppendEvents{AppendEvents: v}
	return b
}

type AppendEventsBuilder struct {
	prototype AppendEvents
}

// NewAppendEventsBuilder returns a builder that constructs [AppendEvents] messages.
func NewAppendEventsBuilder() *AppendEventsBuilder {
	return &AppendEventsBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *AppendEventsBuilder) From(x *AppendEvents) *AppendEventsBuilder {
	b.prototype.Events = x.Events
	return b
}

// Build returns a new [AppendEvents] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *AppendEventsBuilder) Build() *AppendEvents {
	return &AppendEvents{
		Events: b.prototype.Events,
	}
}

// WithEvents configures the builder to set the Events field to v,
// then returns b.
func (b *AppendEventsBuilder) WithEvents(v []*envelopepb.Envelope) *AppendEventsBuilder {
	b.prototype.Events = v
	return b
}

// MustSwitch_Record_Op invokes one of the given functions based on
// the value of x.Op.
//
// It panics if x.Op is nil.
func MustSwitch_Record_Op(
	x *Record,
	caseAppendEvents func(*AppendEvents),
) {
	switch v := x.GetOp().(type) {
	case *Record_AppendEvents:
		caseAppendEvents(v.AppendEvents)
	default:
		panic("MustSwitch_Record_Op: x.Op is nil")
	}
}

// Switch_Record_Op invokes one of the given functions based on
// the value of x.Op.
//
// It calls none() if x.Op is nil.
func Switch_Record_Op(
	x *Record,
	caseAppendEvents func(*AppendEvents),
	none func(),
) {
	switch v := x.GetOp().(type) {
	case *Record_AppendEvents:
		caseAppendEvents(v.AppendEvents)
	default:
		none()
	}
}

// MustMap_Record_Op maps x.Op to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Op,
// and returns that function's result. It panics if x.Op is nil.
func MustMap_Record_Op[T any](
	x *Record,
	caseAppendEvents func(*AppendEvents) T,
) T {
	switch v := x.GetOp().(type) {
	case *Record_AppendEvents:
		return caseAppendEvents(v.AppendEvents)
	default:
		panic("MustMap_Record_Op: x.Op is nil")
	}
}

// Map_Record_Op maps x.Op to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Op,
// and returns that function's result. It calls none() if x.Op is nil.
func Map_Record_Op[T any](
	x *Record,
	caseAppendEvents func(*AppendEvents) T,
	none func() T,
) T {
	switch v := x.GetOp().(type) {
	case *Record_AppendEvents:
		return caseAppendEvents(v.AppendEvents)
	default:
		return none()
	}
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Record] to implement [encoding.BinaryMarshaler].
func (x *Record) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Record] to implement [encoding.BinaryUnmarshaler].
func (x *Record) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*AppendEvents] to implement [encoding.BinaryMarshaler].
func (x *AppendEvents) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*AppendEvents] to implement [encoding.BinaryUnmarshaler].
func (x *AppendEvents) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// SetOffsetBefore sets the x.OffsetBefore field to v, then returns x.
func (x *Record) SetOffsetBefore(v uint64) {
	x.OffsetBefore = v
}

// SetOffsetAfter sets the x.OffsetAfter field to v, then returns x.
func (x *Record) SetOffsetAfter(v uint64) {
	x.OffsetAfter = v
}

// SetAppendEvents sets the x.Op field to a [Record_AppendEvents] value containing v,
// then returns x.
func (x *Record) SetAppendEvents(v *AppendEvents) {
	x.Op = &Record_AppendEvents{AppendEvents: v}
}

// SetEvents sets the x.Events field to v, then returns x.
func (x *AppendEvents) SetEvents(v []*envelopepb.Envelope) {
	x.Events = v
}
