// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/runkit/internal/subsystem/poisonqueue/internal/persistence/message.proto

package persistence

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	identitypb "github.com/dogmatiq/enginekit/protobuf/identitypb"
	proto "google.golang.org/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type QueueMessageBuilder struct {
	prototype QueueMessage
}

// NewQueueMessageBuilder returns a builder that constructs [QueueMessage] messages.
func NewQueueMessageBuilder() *QueueMessageBuilder {
	return &QueueMessageBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *QueueMessageBuilder) From(x *QueueMessage) *QueueMessageBuilder {
	b.prototype.CommandEnvelope = x.CommandEnvelope
	b.prototype.FailedHandler = x.FailedHandler
	b.prototype.EnqueuedAt = x.EnqueuedAt
	return b
}

// Build returns a new [QueueMessage] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *QueueMessageBuilder) Build() *QueueMessage {
	return &QueueMessage{
		CommandEnvelope: b.prototype.CommandEnvelope,
		FailedHandler:   b.prototype.FailedHandler,
		EnqueuedAt:      b.prototype.EnqueuedAt,
	}
}

// WithCommandEnvelope configures the builder to set the CommandEnvelope field to v,
// then returns b.
func (b *QueueMessageBuilder) WithCommandEnvelope(v *envelopepb.Envelope) *QueueMessageBuilder {
	b.prototype.CommandEnvelope = v
	return b
}

// WithFailedHandler configures the builder to set the FailedHandler field to v,
// then returns b.
func (b *QueueMessageBuilder) WithFailedHandler(v *identitypb.Identity) *QueueMessageBuilder {
	b.prototype.FailedHandler = v
	return b
}

// WithEnqueuedAt configures the builder to set the EnqueuedAt field to v,
// then returns b.
func (b *QueueMessageBuilder) WithEnqueuedAt(v *timestamppb.Timestamp) *QueueMessageBuilder {
	b.prototype.EnqueuedAt = v
	return b
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*QueueMessage] to implement [encoding.BinaryMarshaler].
func (x *QueueMessage) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*QueueMessage] to implement [encoding.BinaryUnmarshaler].
func (x *QueueMessage) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// SetCommandEnvelope sets the x.CommandEnvelope field to v, then returns x.
func (x *QueueMessage) SetCommandEnvelope(v *envelopepb.Envelope) {
	x.CommandEnvelope = v
}

// SetFailedHandler sets the x.FailedHandler field to v, then returns x.
func (x *QueueMessage) SetFailedHandler(v *identitypb.Identity) {
	x.FailedHandler = v
}

// SetEnqueuedAt sets the x.EnqueuedAt field to v, then returns x.
func (x *QueueMessage) SetEnqueuedAt(v *timestamppb.Timestamp) {
	x.EnqueuedAt = v
}
