syntax = "proto3";
package runkit.integration.wal.v1;

option go_package = "github.com/dogmatiq/runkit/internal/integration/internal/wal";

import "github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto";
import "github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto";

// Transaction is an entry in the WAL.
message Transaction {
  oneof op {
    HandleCommand handle_command = 1;
    AppendEvents append_events = 2;
    MarkEventsAsAppended mark_events_as_appended = 3;
  }
}

// HandleCommand is an operation that indicates a command is to be
// handled.
message HandleCommand {
  // Command is the envelope containing the command to be handled.
  dogma.protobuf.Envelope command = 1;
}

// AppendEvents is an operation that indicates a command has been handled
// successfully, and the events it produced are to be appended to an event
// stream.
message AppendEvents {
  // CommandId is the ID of the command that was handled.
  dogma.protobuf.UUID command_id = 1;

  // Events is the list of events produced while handling the command, in
  // chronological order.
  repeated dogma.protobuf.Envelope events = 2;

  // StreamId is the ID of the stream to which the events will be appended.
  //
  // It is undefined if the command did not produce any events.
  dogma.protobuf.UUID stream_id = 3;

  // OffsetHint is the next offset of the stream, at the time it was selected
  // for use. The events produced by this message cannot possibly exist before
  // this offset.
  //
  // It is undefined if the command did not produce any events.
  uint64 offset_hint = 4;
}

// MarkEventsAsAppended is an operation that indicates that the events produced
// by a specific command have been appended to an event stream.
message MarkEventsAsAppended {
  // CommandId is the ID of the command that produced the events.
  dogma.protobuf.UUID command_id = 1;

  // // StreamId is the ID of the stream to which the events were appended.
  // //
  // // It is undefined if the command did not produce any events.
  // dogma.protobuf.UUID stream_id = 2;

  // // EventOffset is the offset of the first event.
  // //
  // // It is zero if the command did not produce any events.
  // uint64 event_offset = 3;
}
