// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/runkit/internal/integration/internal/wal/transaction.proto

package wal

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	proto "google.golang.org/protobuf/proto"
)

// TryGetHandleCommand returns x.Op.HandleCommand if x.Op is a [Transaction_HandleCommand].
// Otherwise, ok is false and v is the zero-value.
func (x *Transaction) TryGetHandleCommand() (v *HandleCommand, ok bool) {
	if x, ok := x.GetOp().(*Transaction_HandleCommand); ok {
		return x.HandleCommand, true
	}
	return v, false
}

// TryGetAppendEvents returns x.Op.AppendEvents if x.Op is a [Transaction_AppendEvents].
// Otherwise, ok is false and v is the zero-value.
func (x *Transaction) TryGetAppendEvents() (v *AppendEvents, ok bool) {
	if x, ok := x.GetOp().(*Transaction_AppendEvents); ok {
		return x.AppendEvents, true
	}
	return v, false
}

// TryGetMarkEventsAsAppended returns x.Op.MarkEventsAsAppended if x.Op is a [Transaction_MarkEventsAsAppended].
// Otherwise, ok is false and v is the zero-value.
func (x *Transaction) TryGetMarkEventsAsAppended() (v *MarkEventsAsAppended, ok bool) {
	if x, ok := x.GetOp().(*Transaction_MarkEventsAsAppended); ok {
		return x.MarkEventsAsAppended, true
	}
	return v, false
}

type TransactionBuilder struct {
	prototype Transaction
}

// NewTransactionBuilder returns a builder that constructs [Transaction] messages.
func NewTransactionBuilder() *TransactionBuilder {
	return &TransactionBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *TransactionBuilder) From(x *Transaction) *TransactionBuilder {
	b.prototype.Op = x.Op
	return b
}

// Build returns a new [Transaction] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *TransactionBuilder) Build() *Transaction {
	return &Transaction{
		Op: b.prototype.Op,
	}
}

// WithHandleCommand configures the builder to set the Op field to a
// [Transaction_HandleCommand] value containing v, then returns b
func (b *TransactionBuilder) WithHandleCommand(v *HandleCommand) *TransactionBuilder {
	b.prototype.Op = &Transaction_HandleCommand{HandleCommand: v}
	return b
}

// WithAppendEvents configures the builder to set the Op field to a
// [Transaction_AppendEvents] value containing v, then returns b
func (b *TransactionBuilder) WithAppendEvents(v *AppendEvents) *TransactionBuilder {
	b.prototype.Op = &Transaction_AppendEvents{AppendEvents: v}
	return b
}

// WithMarkEventsAsAppended configures the builder to set the Op field to a
// [Transaction_MarkEventsAsAppended] value containing v, then returns b
func (b *TransactionBuilder) WithMarkEventsAsAppended(v *MarkEventsAsAppended) *TransactionBuilder {
	b.prototype.Op = &Transaction_MarkEventsAsAppended{MarkEventsAsAppended: v}
	return b
}

type HandleCommandBuilder struct {
	prototype HandleCommand
}

// NewHandleCommandBuilder returns a builder that constructs [HandleCommand] messages.
func NewHandleCommandBuilder() *HandleCommandBuilder {
	return &HandleCommandBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *HandleCommandBuilder) From(x *HandleCommand) *HandleCommandBuilder {
	b.prototype.Command = x.Command
	return b
}

// Build returns a new [HandleCommand] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *HandleCommandBuilder) Build() *HandleCommand {
	return &HandleCommand{
		Command: b.prototype.Command,
	}
}

// WithCommand configures the builder to set the Command field to v,
// then returns b.
func (b *HandleCommandBuilder) WithCommand(v *envelopepb.Envelope) *HandleCommandBuilder {
	b.prototype.Command = v
	return b
}

type AppendEventsBuilder struct {
	prototype AppendEvents
}

// NewAppendEventsBuilder returns a builder that constructs [AppendEvents] messages.
func NewAppendEventsBuilder() *AppendEventsBuilder {
	return &AppendEventsBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *AppendEventsBuilder) From(x *AppendEvents) *AppendEventsBuilder {
	b.prototype.CommandId = x.CommandId
	b.prototype.Events = x.Events
	b.prototype.StreamId = x.StreamId
	b.prototype.OffsetHint = x.OffsetHint
	return b
}

// Build returns a new [AppendEvents] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *AppendEventsBuilder) Build() *AppendEvents {
	return &AppendEvents{
		CommandId:  b.prototype.CommandId,
		Events:     b.prototype.Events,
		StreamId:   b.prototype.StreamId,
		OffsetHint: b.prototype.OffsetHint,
	}
}

// WithCommandId configures the builder to set the CommandId field to v,
// then returns b.
func (b *AppendEventsBuilder) WithCommandId(v *uuidpb.UUID) *AppendEventsBuilder {
	b.prototype.CommandId = v
	return b
}

// WithEvents configures the builder to set the Events field to v,
// then returns b.
func (b *AppendEventsBuilder) WithEvents(v []*envelopepb.Envelope) *AppendEventsBuilder {
	b.prototype.Events = v
	return b
}

// WithStreamId configures the builder to set the StreamId field to v,
// then returns b.
func (b *AppendEventsBuilder) WithStreamId(v *uuidpb.UUID) *AppendEventsBuilder {
	b.prototype.StreamId = v
	return b
}

// WithOffsetHint configures the builder to set the OffsetHint field to v,
// then returns b.
func (b *AppendEventsBuilder) WithOffsetHint(v uint64) *AppendEventsBuilder {
	b.prototype.OffsetHint = v
	return b
}

type MarkEventsAsAppendedBuilder struct {
	prototype MarkEventsAsAppended
}

// NewMarkEventsAsAppendedBuilder returns a builder that constructs [MarkEventsAsAppended] messages.
func NewMarkEventsAsAppendedBuilder() *MarkEventsAsAppendedBuilder {
	return &MarkEventsAsAppendedBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *MarkEventsAsAppendedBuilder) From(x *MarkEventsAsAppended) *MarkEventsAsAppendedBuilder {
	b.prototype.CommandId = x.CommandId
	return b
}

// Build returns a new [MarkEventsAsAppended] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *MarkEventsAsAppendedBuilder) Build() *MarkEventsAsAppended {
	return &MarkEventsAsAppended{
		CommandId: b.prototype.CommandId,
	}
}

// WithCommandId configures the builder to set the CommandId field to v,
// then returns b.
func (b *MarkEventsAsAppendedBuilder) WithCommandId(v *uuidpb.UUID) *MarkEventsAsAppendedBuilder {
	b.prototype.CommandId = v
	return b
}

// MustSwitch_Transaction_Op invokes one of the given functions based on
// the value of x.Op.
//
// It panics if x.Op is nil.
func MustSwitch_Transaction_Op(
	x *Transaction,
	caseHandleCommand func(*HandleCommand),
	caseAppendEvents func(*AppendEvents),
	caseMarkEventsAsAppended func(*MarkEventsAsAppended),
) {
	switch v := x.GetOp().(type) {
	case *Transaction_HandleCommand:
		caseHandleCommand(v.HandleCommand)
	case *Transaction_AppendEvents:
		caseAppendEvents(v.AppendEvents)
	case *Transaction_MarkEventsAsAppended:
		caseMarkEventsAsAppended(v.MarkEventsAsAppended)
	default:
		panic("MustSwitch_Transaction_Op: x.Op is nil")
	}
}

// Switch_Transaction_Op invokes one of the given functions based on
// the value of x.Op.
//
// It calls none() if x.Op is nil.
func Switch_Transaction_Op(
	x *Transaction,
	caseHandleCommand func(*HandleCommand),
	caseAppendEvents func(*AppendEvents),
	caseMarkEventsAsAppended func(*MarkEventsAsAppended),
	none func(),
) {
	switch v := x.GetOp().(type) {
	case *Transaction_HandleCommand:
		caseHandleCommand(v.HandleCommand)
	case *Transaction_AppendEvents:
		caseAppendEvents(v.AppendEvents)
	case *Transaction_MarkEventsAsAppended:
		caseMarkEventsAsAppended(v.MarkEventsAsAppended)
	default:
		none()
	}
}

// MustMap_Transaction_Op maps x.Op to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Op,
// and returns that function's result. It panics if x.Op is nil.
func MustMap_Transaction_Op[T any](
	x *Transaction,
	caseHandleCommand func(*HandleCommand) T,
	caseAppendEvents func(*AppendEvents) T,
	caseMarkEventsAsAppended func(*MarkEventsAsAppended) T,
) T {
	switch v := x.GetOp().(type) {
	case *Transaction_HandleCommand:
		return caseHandleCommand(v.HandleCommand)
	case *Transaction_AppendEvents:
		return caseAppendEvents(v.AppendEvents)
	case *Transaction_MarkEventsAsAppended:
		return caseMarkEventsAsAppended(v.MarkEventsAsAppended)
	default:
		panic("MustMap_Transaction_Op: x.Op is nil")
	}
}

// Map_Transaction_Op maps x.Op to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Op,
// and returns that function's result. It calls none() if x.Op is nil.
func Map_Transaction_Op[T any](
	x *Transaction,
	caseHandleCommand func(*HandleCommand) T,
	caseAppendEvents func(*AppendEvents) T,
	caseMarkEventsAsAppended func(*MarkEventsAsAppended) T,
	none func() T,
) T {
	switch v := x.GetOp().(type) {
	case *Transaction_HandleCommand:
		return caseHandleCommand(v.HandleCommand)
	case *Transaction_AppendEvents:
		return caseAppendEvents(v.AppendEvents)
	case *Transaction_MarkEventsAsAppended:
		return caseMarkEventsAsAppended(v.MarkEventsAsAppended)
	default:
		return none()
	}
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Transaction] to implement [encoding.BinaryMarshaler].
func (x *Transaction) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Transaction] to implement [encoding.BinaryUnmarshaler].
func (x *Transaction) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*HandleCommand] to implement [encoding.BinaryMarshaler].
func (x *HandleCommand) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*HandleCommand] to implement [encoding.BinaryUnmarshaler].
func (x *HandleCommand) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*AppendEvents] to implement [encoding.BinaryMarshaler].
func (x *AppendEvents) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*AppendEvents] to implement [encoding.BinaryUnmarshaler].
func (x *AppendEvents) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*MarkEventsAsAppended] to implement [encoding.BinaryMarshaler].
func (x *MarkEventsAsAppended) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*MarkEventsAsAppended] to implement [encoding.BinaryUnmarshaler].
func (x *MarkEventsAsAppended) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// SetHandleCommand sets the x.Op field to a [Transaction_HandleCommand] value containing v,
// then returns x.
func (x *Transaction) SetHandleCommand(v *HandleCommand) {
	x.Op = &Transaction_HandleCommand{HandleCommand: v}
}

// SetAppendEvents sets the x.Op field to a [Transaction_AppendEvents] value containing v,
// then returns x.
func (x *Transaction) SetAppendEvents(v *AppendEvents) {
	x.Op = &Transaction_AppendEvents{AppendEvents: v}
}

// SetMarkEventsAsAppended sets the x.Op field to a [Transaction_MarkEventsAsAppended] value containing v,
// then returns x.
func (x *Transaction) SetMarkEventsAsAppended(v *MarkEventsAsAppended) {
	x.Op = &Transaction_MarkEventsAsAppended{MarkEventsAsAppended: v}
}

// SetCommand sets the x.Command field to v, then returns x.
func (x *HandleCommand) SetCommand(v *envelopepb.Envelope) {
	x.Command = v
}

// SetCommandId sets the x.CommandId field to v, then returns x.
func (x *AppendEvents) SetCommandId(v *uuidpb.UUID) {
	x.CommandId = v
}

// SetEvents sets the x.Events field to v, then returns x.
func (x *AppendEvents) SetEvents(v []*envelopepb.Envelope) {
	x.Events = v
}

// SetStreamId sets the x.StreamId field to v, then returns x.
func (x *AppendEvents) SetStreamId(v *uuidpb.UUID) {
	x.StreamId = v
}

// SetOffsetHint sets the x.OffsetHint field to v, then returns x.
func (x *AppendEvents) SetOffsetHint(v uint64) {
	x.OffsetHint = v
}

// SetCommandId sets the x.CommandId field to v, then returns x.
func (x *MarkEventsAsAppended) SetCommandId(v *uuidpb.UUID) {
	x.CommandId = v
}
