// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: github.com/dogmatiq/runkit/internal/integration/internal/wal/transaction.proto

package wal

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction is an entry in the WAL.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Transaction_HandleCommand
	//	*Transaction_AppendEvents
	//	*Transaction_MarkEventsAsAppended
	Op            isTransaction_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetOp() isTransaction_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Transaction) GetHandleCommand() *HandleCommand {
	if x != nil {
		if x, ok := x.Op.(*Transaction_HandleCommand); ok {
			return x.HandleCommand
		}
	}
	return nil
}

func (x *Transaction) GetAppendEvents() *AppendEvents {
	if x != nil {
		if x, ok := x.Op.(*Transaction_AppendEvents); ok {
			return x.AppendEvents
		}
	}
	return nil
}

func (x *Transaction) GetMarkEventsAsAppended() *MarkEventsAsAppended {
	if x != nil {
		if x, ok := x.Op.(*Transaction_MarkEventsAsAppended); ok {
			return x.MarkEventsAsAppended
		}
	}
	return nil
}

type isTransaction_Op interface {
	isTransaction_Op()
}

type Transaction_HandleCommand struct {
	HandleCommand *HandleCommand `protobuf:"bytes,1,opt,name=handle_command,json=handleCommand,proto3,oneof"`
}

type Transaction_AppendEvents struct {
	AppendEvents *AppendEvents `protobuf:"bytes,2,opt,name=append_events,json=appendEvents,proto3,oneof"`
}

type Transaction_MarkEventsAsAppended struct {
	MarkEventsAsAppended *MarkEventsAsAppended `protobuf:"bytes,3,opt,name=mark_events_as_appended,json=markEventsAsAppended,proto3,oneof"`
}

func (*Transaction_HandleCommand) isTransaction_Op() {}

func (*Transaction_AppendEvents) isTransaction_Op() {}

func (*Transaction_MarkEventsAsAppended) isTransaction_Op() {}

// HandleCommand is an operation that indicates a command is to be
// handled.
type HandleCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command is the envelope containing the command to be handled.
	Command       *envelopepb.Envelope `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleCommand) Reset() {
	*x = HandleCommand{}
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCommand) ProtoMessage() {}

func (x *HandleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCommand.ProtoReflect.Descriptor instead.
func (*HandleCommand) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *HandleCommand) GetCommand() *envelopepb.Envelope {
	if x != nil {
		return x.Command
	}
	return nil
}

// AppendEvents is an operation that indicates a command has been handled
// successfully, and the events it produced are to be appended to an event
// stream.
type AppendEvents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CommandId is the ID of the command that was handled.
	CommandId *uuidpb.UUID `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Events is the list of events produced while handling the command, in
	// chronological order.
	Events []*envelopepb.Envelope `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// StreamId is the ID of the stream to which the events will be appended.
	//
	// It is undefined if the command did not produce any events.
	StreamId *uuidpb.UUID `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// OffsetHint is the next offset of the stream, at the time it was selected
	// for use. The events produced by this message cannot possibly exist before
	// this offset.
	//
	// It is undefined if the command did not produce any events.
	OffsetHint    uint64 `protobuf:"varint,4,opt,name=offset_hint,json=offsetHint,proto3" json:"offset_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEvents) Reset() {
	*x = AppendEvents{}
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEvents) ProtoMessage() {}

func (x *AppendEvents) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEvents.ProtoReflect.Descriptor instead.
func (*AppendEvents) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEvents) GetCommandId() *uuidpb.UUID {
	if x != nil {
		return x.CommandId
	}
	return nil
}

func (x *AppendEvents) GetEvents() []*envelopepb.Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AppendEvents) GetStreamId() *uuidpb.UUID {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *AppendEvents) GetOffsetHint() uint64 {
	if x != nil {
		return x.OffsetHint
	}
	return 0
}

// MarkEventsAsAppended is an operation that indicates that the events produced
// by a specific command have been appended to an event stream.
type MarkEventsAsAppended struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CommandId is the ID of the command that produced the events.
	CommandId     *uuidpb.UUID `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkEventsAsAppended) Reset() {
	*x = MarkEventsAsAppended{}
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkEventsAsAppended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkEventsAsAppended) ProtoMessage() {}

func (x *MarkEventsAsAppended) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkEventsAsAppended.ProtoReflect.Descriptor instead.
func (*MarkEventsAsAppended) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *MarkEventsAsAppended) GetCommandId() *uuidpb.UUID {
	if x != nil {
		return x.CommandId
	}
	return nil
}

var File_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDesc = "" +
	"\n" +
	"Ngithub.com/dogmatiq/runkit/internal/integration/internal/wal/transaction.proto\x12\x19runkit.integration.wal.v1\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\x1a@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\"\xa0\x02\n" +
	"\vTransaction\x12Q\n" +
	"\x0ehandle_command\x18\x01 \x01(\v2(.runkit.integration.wal.v1.HandleCommandH\x00R\rhandleCommand\x12N\n" +
	"\rappend_events\x18\x02 \x01(\v2'.runkit.integration.wal.v1.AppendEventsH\x00R\fappendEvents\x12h\n" +
	"\x17mark_events_as_appended\x18\x03 \x01(\v2/.runkit.integration.wal.v1.MarkEventsAsAppendedH\x00R\x14markEventsAsAppendedB\x04\n" +
	"\x02op\"C\n" +
	"\rHandleCommand\x122\n" +
	"\acommand\x18\x01 \x01(\v2\x18.dogma.protobuf.EnvelopeR\acommand\"\xc9\x01\n" +
	"\fAppendEvents\x123\n" +
	"\n" +
	"command_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\tcommandId\x120\n" +
	"\x06events\x18\x02 \x03(\v2\x18.dogma.protobuf.EnvelopeR\x06events\x121\n" +
	"\tstream_id\x18\x03 \x01(\v2\x14.dogma.protobuf.UUIDR\bstreamId\x12\x1f\n" +
	"\voffset_hint\x18\x04 \x01(\x04R\n" +
	"offsetHint\"K\n" +
	"\x14MarkEventsAsAppended\x123\n" +
	"\n" +
	"command_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\tcommandIdB>Z<github.com/dogmatiq/runkit/internal/integration/internal/walb\x06proto3"

var (
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescData []byte
)

func file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDescData
}

var file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_goTypes = []any{
	(*Transaction)(nil),          // 0: runkit.integration.wal.v1.Transaction
	(*HandleCommand)(nil),        // 1: runkit.integration.wal.v1.HandleCommand
	(*AppendEvents)(nil),         // 2: runkit.integration.wal.v1.AppendEvents
	(*MarkEventsAsAppended)(nil), // 3: runkit.integration.wal.v1.MarkEventsAsAppended
	(*envelopepb.Envelope)(nil),  // 4: dogma.protobuf.Envelope
	(*uuidpb.UUID)(nil),          // 5: dogma.protobuf.UUID
}
var file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_depIdxs = []int32{
	1, // 0: runkit.integration.wal.v1.Transaction.handle_command:type_name -> runkit.integration.wal.v1.HandleCommand
	2, // 1: runkit.integration.wal.v1.Transaction.append_events:type_name -> runkit.integration.wal.v1.AppendEvents
	3, // 2: runkit.integration.wal.v1.Transaction.mark_events_as_appended:type_name -> runkit.integration.wal.v1.MarkEventsAsAppended
	4, // 3: runkit.integration.wal.v1.HandleCommand.command:type_name -> dogma.protobuf.Envelope
	5, // 4: runkit.integration.wal.v1.AppendEvents.command_id:type_name -> dogma.protobuf.UUID
	4, // 5: runkit.integration.wal.v1.AppendEvents.events:type_name -> dogma.protobuf.Envelope
	5, // 6: runkit.integration.wal.v1.AppendEvents.stream_id:type_name -> dogma.protobuf.UUID
	5, // 7: runkit.integration.wal.v1.MarkEventsAsAppended.command_id:type_name -> dogma.protobuf.UUID
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_init()
}
func file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_init() {
	if File_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto != nil {
		return
	}
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_HandleCommand)(nil),
		(*Transaction_AppendEvents)(nil),
		(*Transaction_MarkEventsAsAppended)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto = out.File
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_goTypes = nil
	file_github_com_dogmatiq_runkit_internal_integration_internal_wal_transaction_proto_depIdxs = nil
}
