// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/persistence/transaction.proto

package persistence

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	proto "google.golang.org/protobuf/proto"
)

// TryGetAppendOperation returns x.Op.AppendOperation if x.Op is a [Transaction_AppendOperation].
// Otherwise, ok is false and v is the zero-value.
func (x *Transaction) TryGetAppendOperation() (v *AppendOperation, ok bool) {
	if x, ok := x.GetOp().(*Transaction_AppendOperation); ok {
		return x.AppendOperation, true
	}
	return v, false
}

type TransactionBuilder struct {
	prototype Transaction
}

// NewTransactionBuilder returns a builder that constructs [Transaction] messages.
func NewTransactionBuilder() *TransactionBuilder {
	return &TransactionBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *TransactionBuilder) From(x *Transaction) *TransactionBuilder {
	b.prototype.MetaData = x.MetaData
	b.prototype.Op = x.Op
	return b
}

// Build returns a new [Transaction] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *TransactionBuilder) Build() *Transaction {
	return &Transaction{
		MetaData: b.prototype.MetaData,
		Op:       b.prototype.Op,
	}
}

// WithMetaData configures the builder to set the MetaData field to v,
// then returns b.
func (b *TransactionBuilder) WithMetaData(v *Transaction_MetaData) *TransactionBuilder {
	b.prototype.MetaData = v
	return b
}

// WithAppendOperation configures the builder to set the Op field to a
// [Transaction_AppendOperation] value containing v, then returns b
func (b *TransactionBuilder) WithAppendOperation(v *AppendOperation) *TransactionBuilder {
	b.prototype.Op = &Transaction_AppendOperation{AppendOperation: v}
	return b
}

type Transaction_MetaDataBuilder struct {
	prototype Transaction_MetaData
}

// NewTransaction_MetaDataBuilder returns a builder that constructs [Transaction_MetaData] messages.
func NewTransaction_MetaDataBuilder() *Transaction_MetaDataBuilder {
	return &Transaction_MetaDataBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *Transaction_MetaDataBuilder) From(x *Transaction_MetaData) *Transaction_MetaDataBuilder {
	b.prototype.OffsetBefore = x.OffsetBefore
	b.prototype.OffsetAfter = x.OffsetAfter
	return b
}

// Build returns a new [Transaction_MetaData] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *Transaction_MetaDataBuilder) Build() *Transaction_MetaData {
	return &Transaction_MetaData{
		OffsetBefore: b.prototype.OffsetBefore,
		OffsetAfter:  b.prototype.OffsetAfter,
	}
}

// WithOffsetBefore configures the builder to set the OffsetBefore field to v,
// then returns b.
func (b *Transaction_MetaDataBuilder) WithOffsetBefore(v uint64) *Transaction_MetaDataBuilder {
	b.prototype.OffsetBefore = v
	return b
}

// WithOffsetAfter configures the builder to set the OffsetAfter field to v,
// then returns b.
func (b *Transaction_MetaDataBuilder) WithOffsetAfter(v uint64) *Transaction_MetaDataBuilder {
	b.prototype.OffsetAfter = v
	return b
}

type AppendOperationBuilder struct {
	prototype AppendOperation
}

// NewAppendOperationBuilder returns a builder that constructs [AppendOperation] messages.
func NewAppendOperationBuilder() *AppendOperationBuilder {
	return &AppendOperationBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *AppendOperationBuilder) From(x *AppendOperation) *AppendOperationBuilder {
	b.prototype.Events = x.Events
	return b
}

// Build returns a new [AppendOperation] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *AppendOperationBuilder) Build() *AppendOperation {
	return &AppendOperation{
		Events: b.prototype.Events,
	}
}

// WithEvents configures the builder to set the Events field to v,
// then returns b.
func (b *AppendOperationBuilder) WithEvents(v []*envelopepb.Envelope) *AppendOperationBuilder {
	b.prototype.Events = v
	return b
}

// MustSwitch_Transaction_Op invokes one of the given functions based on
// the value of x.Op.
//
// It panics if x.Op is nil.
func MustSwitch_Transaction_Op(
	x *Transaction,
	caseAppendOperation func(*AppendOperation),
) {
	switch v := x.GetOp().(type) {
	case *Transaction_AppendOperation:
		caseAppendOperation(v.AppendOperation)
	default:
		panic("MustSwitch_Transaction_Op: x.Op is nil")
	}
}

// Switch_Transaction_Op invokes one of the given functions based on
// the value of x.Op.
//
// It calls none() if x.Op is nil.
func Switch_Transaction_Op(
	x *Transaction,
	caseAppendOperation func(*AppendOperation),
	none func(),
) {
	switch v := x.GetOp().(type) {
	case *Transaction_AppendOperation:
		caseAppendOperation(v.AppendOperation)
	default:
		none()
	}
}

// MustMap_Transaction_Op maps x.Op to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Op,
// and returns that function's result. It panics if x.Op is nil.
func MustMap_Transaction_Op[T any](
	x *Transaction,
	caseAppendOperation func(*AppendOperation) T,
) T {
	switch v := x.GetOp().(type) {
	case *Transaction_AppendOperation:
		return caseAppendOperation(v.AppendOperation)
	default:
		panic("MustMap_Transaction_Op: x.Op is nil")
	}
}

// Map_Transaction_Op maps x.Op to a value of type T by invoking
// one of the given functions.
//
// It invokes the function that corresponds to the value of x.Op,
// and returns that function's result. It calls none() if x.Op is nil.
func Map_Transaction_Op[T any](
	x *Transaction,
	caseAppendOperation func(*AppendOperation) T,
	none func() T,
) T {
	switch v := x.GetOp().(type) {
	case *Transaction_AppendOperation:
		return caseAppendOperation(v.AppendOperation)
	default:
		return none()
	}
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Transaction] to implement [encoding.BinaryMarshaler].
func (x *Transaction) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Transaction] to implement [encoding.BinaryUnmarshaler].
func (x *Transaction) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*Transaction_MetaData] to implement [encoding.BinaryMarshaler].
func (x *Transaction_MetaData) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*Transaction_MetaData] to implement [encoding.BinaryUnmarshaler].
func (x *Transaction_MetaData) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*AppendOperation] to implement [encoding.BinaryMarshaler].
func (x *AppendOperation) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*AppendOperation] to implement [encoding.BinaryUnmarshaler].
func (x *AppendOperation) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// SetMetaData sets the x.MetaData field to v, then returns x.
func (x *Transaction) SetMetaData(v *Transaction_MetaData) {
	x.MetaData = v
}

// SetAppendOperation sets the x.Op field to a [Transaction_AppendOperation] value containing v,
// then returns x.
func (x *Transaction) SetAppendOperation(v *AppendOperation) {
	x.Op = &Transaction_AppendOperation{AppendOperation: v}
}

// SetOffsetBefore sets the x.OffsetBefore field to v, then returns x.
func (x *Transaction_MetaData) SetOffsetBefore(v uint64) {
	x.OffsetBefore = v
}

// SetOffsetAfter sets the x.OffsetAfter field to v, then returns x.
func (x *Transaction_MetaData) SetOffsetAfter(v uint64) {
	x.OffsetAfter = v
}

// SetEvents sets the x.Events field to v, then returns x.
func (x *AppendOperation) SetEvents(v []*envelopepb.Envelope) {
	x.Events = v
}
