// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/transaction/transaction.proto

package transaction

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	uuidpb "github.com/dogmatiq/enginekit/protobuf/uuidpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction is a modification to the state of an event stream partition.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MetaData contains metadata about the transaction.
	MetaData *Transaction_MetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	// Op is the operation being performed.
	//
	// Types that are valid to be assigned to Op:
	//
	//	*Transaction_AppendEventsOperation
	Op            isTransaction_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMetaData() *Transaction_MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Transaction) GetOp() isTransaction_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Transaction) GetAppendEventsOperation() *AppendEventsOperation {
	if x != nil {
		if x, ok := x.Op.(*Transaction_AppendEventsOperation); ok {
			return x.AppendEventsOperation
		}
	}
	return nil
}

type isTransaction_Op interface {
	isTransaction_Op()
}

type Transaction_AppendEventsOperation struct {
	AppendEventsOperation *AppendEventsOperation `protobuf:"bytes,2,opt,name=append_events_operation,json=appendEventsOperation,proto3,oneof"`
}

func (*Transaction_AppendEventsOperation) isTransaction_Op() {}

// AppendEventsOperation is an operation that appends events to the partition.
type AppendEventsOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RequestId is the unique identifier of the request that resulted in this
	// operation.
	RequestId *uuidpb.UUID `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Events is the ordered list of envelopes containing the appended events.
	Events        []*envelopepb.Envelope `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventsOperation) Reset() {
	*x = AppendEventsOperation{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventsOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventsOperation) ProtoMessage() {}

func (x *AppendEventsOperation) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventsOperation.ProtoReflect.Descriptor instead.
func (*AppendEventsOperation) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEventsOperation) GetRequestId() *uuidpb.UUID {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *AppendEventsOperation) GetEvents() []*envelopepb.Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type Transaction_MetaData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OffsetBefore is the highest offset within the partition before this
	// transaction occurred.
	OffsetBefore uint64 `protobuf:"varint,1,opt,name=offset_before,json=offsetBefore,proto3" json:"offset_before,omitempty"`
	// OffsetAfter is the highest offset within the partition after this
	// transaction occurred.
	//
	// It is the same as OffsetBefore plus the number of events appended by this
	// transaction, if any.
	OffsetAfter   uint64 `protobuf:"varint,2,opt,name=offset_after,json=offsetAfter,proto3" json:"offset_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_MetaData) Reset() {
	*x = Transaction_MetaData{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_MetaData) ProtoMessage() {}

func (x *Transaction_MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_MetaData.ProtoReflect.Descriptor instead.
func (*Transaction_MetaData) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transaction_MetaData) GetOffsetBefore() uint64 {
	if x != nil {
		return x.OffsetBefore
	}
	return 0
}

func (x *Transaction_MetaData) GetOffsetAfter() uint64 {
	if x != nil {
		return x.OffsetAfter
	}
	return 0
}

var File_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"`github.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/transaction/transaction.proto\x12!runkit.eventstream.transaction.v1\x1a@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\x1a8github.com/dogmatiq/enginekit/protobuf/uuidpb/uuid.proto\"\xb1\x02\n" +
	"\vTransaction\x12T\n" +
	"\tmeta_data\x18\x01 \x01(\v27.runkit.eventstream.transaction.v1.Transaction.MetaDataR\bmetaData\x12r\n" +
	"\x17append_events_operation\x18\x02 \x01(\v28.runkit.eventstream.transaction.v1.AppendEventsOperationH\x00R\x15appendEventsOperation\x1aR\n" +
	"\bMetaData\x12#\n" +
	"\roffset_before\x18\x01 \x01(\x04R\foffsetBefore\x12!\n" +
	"\foffset_after\x18\x02 \x01(\x04R\voffsetAfterB\x04\n" +
	"\x02op\"~\n" +
	"\x15AppendEventsOperation\x123\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x14.dogma.protobuf.UUIDR\trequestId\x120\n" +
	"\x06events\x18\x02 \x03(\v2\x18.dogma.protobuf.EnvelopeR\x06eventsBPZNgithub.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/transactionb\x06proto3"

var (
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescData []byte
)

func file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDescData
}

var file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: runkit.eventstream.transaction.v1.Transaction
	(*AppendEventsOperation)(nil), // 1: runkit.eventstream.transaction.v1.AppendEventsOperation
	(*Transaction_MetaData)(nil),  // 2: runkit.eventstream.transaction.v1.Transaction.MetaData
	(*uuidpb.UUID)(nil),           // 3: dogma.protobuf.UUID
	(*envelopepb.Envelope)(nil),   // 4: dogma.protobuf.Envelope
}
var file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_depIdxs = []int32{
	2, // 0: runkit.eventstream.transaction.v1.Transaction.meta_data:type_name -> runkit.eventstream.transaction.v1.Transaction.MetaData
	1, // 1: runkit.eventstream.transaction.v1.Transaction.append_events_operation:type_name -> runkit.eventstream.transaction.v1.AppendEventsOperation
	3, // 2: runkit.eventstream.transaction.v1.AppendEventsOperation.request_id:type_name -> dogma.protobuf.UUID
	4, // 3: runkit.eventstream.transaction.v1.AppendEventsOperation.events:type_name -> dogma.protobuf.Envelope
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_init()
}
func file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_init() {
	if File_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto != nil {
		return
	}
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_AppendEventsOperation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto = out.File
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_goTypes = nil
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_transaction_transaction_proto_depIdxs = nil
}
