// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/runkit/internal/heartbeat/internal/heartbeatpb/heartbeat.proto

package heartbeatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeartbeatRecord stores the presence information for a single node.
type HeartbeatRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is the advertise address of the node (host:port).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// expires_at is the time after which this record may be considered stale.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRecord) Reset() {
	*x = HeartbeatRecord{}
	mi := &file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRecord) ProtoMessage() {}

func (x *HeartbeatRecord) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRecord.ProtoReflect.Descriptor instead.
func (*HeartbeatRecord) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatRecord) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDesc = "" +
	"\n" +
	"Rgithub.com/dogmatiq/runkit/internal/heartbeat/internal/heartbeatpb/heartbeat.proto\x12\x19dogmatiq.runkit.heartbeat\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\x0fHeartbeatRecord\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtBDZBgithub.com/dogmatiq/runkit/internal/heartbeat/internal/heartbeatpbb\x06proto3"

var (
	file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescData []byte
)

func file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDescData
}

var file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_goTypes = []any{
	(*HeartbeatRecord)(nil),       // 0: dogmatiq.runkit.heartbeat.HeartbeatRecord
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_depIdxs = []int32{
	1, // 0: dogmatiq.runkit.heartbeat.HeartbeatRecord.expires_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_init()
}
func file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_init() {
	if File_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto = out.File
	file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_goTypes = nil
	file_github_com_dogmatiq_runkit_internal_heartbeat_internal_heartbeatpb_heartbeat_proto_depIdxs = nil
}
