// Code generated by protoc-gen-go-primo. DO NOT EDIT.
// versions:
// 	protoc-gen-go-primo v
// 	protoc              v6.33.1
// source: github.com/dogmatiq/runkit/internal/heartbeat/internal/heartbeatpb/heartbeat.proto

package heartbeatpb

import (
	proto "google.golang.org/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type HeartbeatRecordBuilder struct {
	prototype HeartbeatRecord
}

// NewHeartbeatRecordBuilder returns a builder that constructs [HeartbeatRecord] messages.
func NewHeartbeatRecordBuilder() *HeartbeatRecordBuilder {
	return &HeartbeatRecordBuilder{}
}

// From configures the builder to use x as the prototype for new messages,
// then returns b.
//
// It performs a shallow copy of x, such that any changes made via the builder
// do not modify x. It does not make a copy of the field values themselves.
func (b *HeartbeatRecordBuilder) From(x *HeartbeatRecord) *HeartbeatRecordBuilder {
	b.prototype.Address = x.Address
	b.prototype.ExpiresAt = x.ExpiresAt
	return b
}

// Build returns a new [HeartbeatRecord] containing the values configured via the builder.
//
// Each call returns a new message, such that future changes to the builder do
// not modify previously constructed messages.
func (b *HeartbeatRecordBuilder) Build() *HeartbeatRecord {
	return &HeartbeatRecord{
		Address:   b.prototype.Address,
		ExpiresAt: b.prototype.ExpiresAt,
	}
}

// WithAddress configures the builder to set the Address field to v,
// then returns b.
func (b *HeartbeatRecordBuilder) WithAddress(v string) *HeartbeatRecordBuilder {
	b.prototype.Address = v
	return b
}

// WithExpiresAt configures the builder to set the ExpiresAt field to v,
// then returns b.
func (b *HeartbeatRecordBuilder) WithExpiresAt(v *timestamppb.Timestamp) *HeartbeatRecordBuilder {
	b.prototype.ExpiresAt = v
	return b
}

// MarshalBinary returns the binary representation of the message, equivalent to
// calling proto.Marshal(x).
//
// It allows [*HeartbeatRecord] to implement [encoding.BinaryMarshaler].
func (x *HeartbeatRecord) MarshalBinary() ([]byte, error) {
	return proto.Marshal(x)
}

// UnmarshalBinary populates x from its binary representation, equivalent to
// calling proto.Unmarshal(data, x).
//
// It allows [*HeartbeatRecord] to implement [encoding.BinaryUnmarshaler].
func (x *HeartbeatRecord) UnmarshalBinary(data []byte) error {
	return proto.Unmarshal(data, x)
}

// SetAddress sets the x.Address field to v, then returns x.
func (x *HeartbeatRecord) SetAddress(v string) {
	x.Address = v
}

// SetExpiresAt sets the x.ExpiresAt field to v, then returns x.
func (x *HeartbeatRecord) SetExpiresAt(v *timestamppb.Timestamp) {
	x.ExpiresAt = v
}
