syntax = "proto3";
package dogma.runkit.heartbeat;

option go_package = "github.com/dogmatiq/runkit/internal/heartbeat/internal/heartbeatpb";

import "google/protobuf/timestamp.proto";

// HeartbeatRecord stores the presence information for a single node.
message HeartbeatRecord {
    // Addresses are the network addresses advertised to the other nodes in the
    // cluster.
    repeated string addresses = 1;

    // ExpiresAt is the time after which this record may be considered stale.
    google.protobuf.Timestamp expires_at = 2;
}
