syntax = "proto3";
package runkit.eventstream.persistence.v1;

option go_package = "github.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/persistence";

import "github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto";

// Transaction is a modification to the state of an event stream partition.
message Transaction {
  message MetaData {
    // OffsetBefore is the highest offset within the partition before this
    // transaction occurred.
    uint64 offset_before = 1;

    // OffsetAfter is the highest offset within the partition after this
    // transaction occurred.
    //
    // It is the same as OffsetBefore plus the number of events appended by this
    // transaction, if any.
    uint64 offset_after = 2;
  }

  // MetaData contains metadata about the transaction.
  MetaData meta_data = 1;

  // Op is the operation being performed.
  oneof op { AppendOperation append_operation = 2; }
}

// AppendOperation is an operation that appends events to the partition.
message AppendOperation {
  // Events is the ordered list of envelopes containing the appended events.
  repeated dogma.protobuf.Envelope events = 1;
}
