// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/persistence/transaction.proto

package persistence

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction is a modification to the state of an event stream partition.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MetaData contains metadata about the transaction.
	MetaData *Transaction_MetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	// Op is the operation being performed.
	//
	// Types that are valid to be assigned to Op:
	//
	//	*Transaction_AppendOperation
	Op            isTransaction_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMetaData() *Transaction_MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *Transaction) GetOp() isTransaction_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Transaction) GetAppendOperation() *AppendOperation {
	if x != nil {
		if x, ok := x.Op.(*Transaction_AppendOperation); ok {
			return x.AppendOperation
		}
	}
	return nil
}

type isTransaction_Op interface {
	isTransaction_Op()
}

type Transaction_AppendOperation struct {
	AppendOperation *AppendOperation `protobuf:"bytes,2,opt,name=append_operation,json=appendOperation,proto3,oneof"`
}

func (*Transaction_AppendOperation) isTransaction_Op() {}

// AppendOperation is an operation that appends events to the partition.
type AppendOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events is the ordered list of envelopes containing the appended events.
	Events        []*envelopepb.Envelope `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendOperation) Reset() {
	*x = AppendOperation{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendOperation) ProtoMessage() {}

func (x *AppendOperation) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendOperation.ProtoReflect.Descriptor instead.
func (*AppendOperation) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *AppendOperation) GetEvents() []*envelopepb.Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type Transaction_MetaData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OffsetBefore is the highest offset within the partition before this
	// transaction occurred.
	OffsetBefore uint64 `protobuf:"varint,1,opt,name=offset_before,json=offsetBefore,proto3" json:"offset_before,omitempty"`
	// OffsetAfter is the highest offset within the partition after this
	// transaction occurred.
	//
	// It is the same as OffsetBefore plus the number of events appended by this
	// transaction, if any.
	OffsetAfter   uint64 `protobuf:"varint,2,opt,name=offset_after,json=offsetAfter,proto3" json:"offset_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_MetaData) Reset() {
	*x = Transaction_MetaData{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_MetaData) ProtoMessage() {}

func (x *Transaction_MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_MetaData.ProtoReflect.Descriptor instead.
func (*Transaction_MetaData) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transaction_MetaData) GetOffsetBefore() uint64 {
	if x != nil {
		return x.OffsetBefore
	}
	return 0
}

func (x *Transaction_MetaData) GetOffsetAfter() uint64 {
	if x != nil {
		return x.OffsetAfter
	}
	return 0
}

var File_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDesc = "" +
	"\n" +
	"`github.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/persistence/transaction.proto\x12!runkit.persistence.eventstream.v1\x1a@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\"\x9e\x02\n" +
	"\vTransaction\x12T\n" +
	"\tmeta_data\x18\x01 \x01(\v27.runkit.persistence.eventstream.v1.Transaction.MetaDataR\bmetaData\x12_\n" +
	"\x10append_operation\x18\x02 \x01(\v22.runkit.persistence.eventstream.v1.AppendOperationH\x00R\x0fappendOperation\x1aR\n" +
	"\bMetaData\x12#\n" +
	"\roffset_before\x18\x01 \x01(\x04R\foffsetBefore\x12!\n" +
	"\foffset_after\x18\x02 \x01(\x04R\voffsetAfterB\x04\n" +
	"\x02op\"C\n" +
	"\x0fAppendOperation\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.dogma.protobuf.EnvelopeR\x06eventsBPZNgithub.com/dogmatiq/runkit/internal/subsystem/eventstream/internal/persistenceb\x06proto3"

var (
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescData []byte
)

func file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDescData
}

var file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_goTypes = []any{
	(*Transaction)(nil),          // 0: runkit.persistence.eventstream.v1.Transaction
	(*AppendOperation)(nil),      // 1: runkit.persistence.eventstream.v1.AppendOperation
	(*Transaction_MetaData)(nil), // 2: runkit.persistence.eventstream.v1.Transaction.MetaData
	(*envelopepb.Envelope)(nil),  // 3: dogma.protobuf.Envelope
}
var file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_depIdxs = []int32{
	2, // 0: runkit.persistence.eventstream.v1.Transaction.meta_data:type_name -> runkit.persistence.eventstream.v1.Transaction.MetaData
	1, // 1: runkit.persistence.eventstream.v1.Transaction.append_operation:type_name -> runkit.persistence.eventstream.v1.AppendOperation
	3, // 2: runkit.persistence.eventstream.v1.AppendOperation.events:type_name -> dogma.protobuf.Envelope
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_init()
}
func file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_init() {
	if File_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto != nil {
		return
	}
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_AppendOperation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto = out.File
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_goTypes = nil
	file_github_com_dogmatiq_runkit_internal_subsystem_eventstream_internal_persistence_transaction_proto_depIdxs = nil
}
