package xtesting

import (
	"reflect"
	"testing"

	"github.com/dogmatiq/dapper"
	"github.com/dogmatiq/dogma"
	"github.com/dogmatiq/enginekit/protobuf/envelopepb"
	"github.com/dogmatiq/enginekit/protobuf/uuidpb"
	"github.com/dogmatiq/reference-engine/internal/x/xsql"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateEventStreams creates the given number of event streams.
func CreateEventStreams(
	t testing.TB,
	x xsql.Executor,
	count int,
) []*uuidpb.UUID {
	t.Helper()

	streamIDs := make([]*uuidpb.UUID, count)

	for i := range count {
		streamIDs[i] = uuidpb.Generate()

		if _, err := x.ExecContext(
			t.Context(),
			`INSERT INTO eventstream.streams (id) VALUES ($1)`,
			xsql.UUID(streamIDs[i]),
		); err != nil {
			t.Fatal(err)
		}
	}

	return streamIDs
}

// PopulateEventStreams creates event streams and populates them with events
// generated by the given function.
//
// Each element of counts specifies the number of events to append to one
// stream, so the number of streams created equals len(counts). Events are
// distributed by cycling through the streams, appending one event at a time to
// each in turn.
//
// It returns the stream IDs that were created.
func PopulateEventStreams(
	t testing.TB,
	x xsql.Executor,
	fn func(streamID *uuidpb.UUID, offset uint64) dogma.Event,
	counts ...uint64,
) []*uuidpb.UUID {
	t.Helper()

	streamIDs := CreateEventStreams(t, x, len(counts))
	offsets := make([]uint64, len(counts))

	for {
		progress := false

		for idx, streamID := range streamIDs {
			if offsets[idx] >= counts[idx] {
				continue
			}

			event := fn(streamID, offsets[idx])
			env := packTestEvent(t, event)

			if _, err := x.ExecContext(
				t.Context(),
				`SELECT eventstream.append(
					$1,
					$2,
					NULL, -- aggregate handler key
					NULL, -- aggregate instance ID
					ARRAY[ROW($3, $4, $5)::eventstream.event]
				)`,
				xsql.UUID(streamID),
				xsql.UUID(env.GetHeader().GetCorrelationId()),
				xsql.UUID(env.GetBody().GetMessageId()),
				xsql.UUID(env.GetBody().GetMessage().GetTypeId()),
				xsql.Envelope(env),
			); err != nil {
				t.Fatal(err)
			}

			offsets[idx]++
			progress = true
		}

		if !progress {
			return streamIDs
		}
	}
}

// ExpectEventStreamCount asserts that the number of event streams in the database
// matches the given value.
func ExpectEventStreamCount(
	t testing.TB,
	q xsql.Querier,
	want int,
) {
	t.Helper()

	ExpectQueryResult(
		t,
		"event stream count",
		want,
		q,
		`SELECT COUNT(*)
		FROM eventstream.streams`,
	)
}

// ExpectEventCount asserts that the total number of events in the database
// matches the given value.
func ExpectEventCount(
	t testing.TB,
	q xsql.Querier,
	want int,
) {
	t.Helper()

	ExpectQueryResult(
		t,
		"event count",
		want,
		q,
		`SELECT COUNT(*)
		FROM eventstream.events`,
	)
}

// ExpectContiguousEvents asserts that an event stream contains the given
// events, starting at the given offset, with no gaps.
func ExpectContiguousEvents(
	t testing.TB,
	q xsql.Querier,
	streamID *uuidpb.UUID,
	offset uint64,
	want ...dogma.Event,
) {
	t.Helper()

	rows, err := q.QueryContext(
		t.Context(),
		`SELECT
			e.stream_offset,
			e.envelope
		FROM eventstream.events AS e
		WHERE e.stream_id = $1
		AND e.stream_offset >= $2
		ORDER BY e.stream_offset
		LIMIT $3`,
		xsql.UUID(streamID),
		offset,
		len(want),
	)
	if err != nil {
		t.Fatalf("unable to query events: %v", err)
	}
	defer rows.Close()

	wantOffset := offset

	for rows.Next() {
		var gotOffset uint64
		env := &envelopepb.Envelope{}
		if err := rows.Scan(&gotOffset, xsql.Envelope(env)); err != nil {
			t.Fatalf("unable to scan event: %v", err)
		}

		if gotOffset != wantOffset {
			t.Fatalf(
				"unexpected event stream offset: got %d, want %d",
				gotOffset,
				wantOffset,
			)
		}

		got, err := envelopepb.Unpack[dogma.Event](env)
		if err != nil {
			t.Fatalf("unable to unpack event: %v", err)
		}

		wantEvent := want[0]
		want = want[1:]

		if !reflect.DeepEqual(got, wantEvent) {
			t.Logf("unexpected event at offset %d:", gotOffset)
			t.Logf("+++ got:\n%s", dapper.Format(got))
			t.Logf("--- want:\n%s", dapper.Format(wantEvent))
			t.FailNow()
		}

		wantOffset++
	}

	if len(want) != 0 {
		t.Fatalf("missing %d event(s)", len(want))
	}
}

// ExpectContiguousEventEnvelopes asserts that an event stream contains the
// given event envelopes, starting at the given offset.
func ExpectContiguousEventEnvelopes(
	t testing.TB,
	q xsql.Querier,
	streamID *uuidpb.UUID,
	offset uint64,
	want ...*envelopepb.Envelope,
) {
	t.Helper()

	rows, err := q.QueryContext(
		t.Context(),
		`SELECT
			e.stream_offset,
			e.envelope
		FROM eventstream.events AS e
		WHERE e.stream_id = $1
		AND e.stream_offset >= $2
		ORDER BY e.stream_offset
		LIMIT $3`,
		xsql.UUID(streamID),
		offset,
		len(want),
	)
	if err != nil {
		t.Fatalf("unable to query events: %v", err)
	}
	defer rows.Close()

	wantOffset := offset

	for rows.Next() {
		var (
			gotOffset   uint64
			gotEnvelope = &envelopepb.Envelope{}
		)

		if err := rows.Scan(
			&gotOffset,
			xsql.Envelope(gotEnvelope),
		); err != nil {
			t.Fatalf("unable to scan event envelope: %v", err)
		}

		if gotOffset != wantOffset {
			t.Fatalf(
				"unexpected event stream offset: got %d, want %d",
				gotOffset,
				wantOffset,
			)
		}

		wantEnvelope := want[0]
		want = want[1:]

		if !proto.Equal(gotEnvelope, wantEnvelope) {
			t.Logf("unexpected event envelope at offset %d:", gotOffset)
			t.Logf("+++ got:\n%s", prototext.Format(gotEnvelope))
			t.Logf("--- want:\n%s", prototext.Format(wantEnvelope))
			t.FailNow()
		}

		wantOffset++
	}

	if len(want) != 0 {
		t.Fatalf(
			"missing event at offset: %d",
			wantOffset,
		)
	}
}

// WaitForHandlerToConsumeAllEvents waits until the handler with the given key
// has caught up to the tail of all non-empty event streams. If this does not
// occur within [WaitTimeout], the test fails.
//
// It assumes that all events on all streams are of types that the handler
// consumes. If that is not the case this assertion will hang until it times out.
func WaitForHandlerToConsumeAllEvents(
	t testing.TB,
	q xsql.Querier,
	handlerKey string,
) {
	t.Helper()

	WaitForQueryResult(
		t,
		"no unconsumed events",
		0,
		q,
		`SELECT COUNT(*)
		FROM eventstream.streams AS s
		LEFT JOIN eventstream.handler_checkpoints AS h
			ON h.handler_key = $1
			AND h.stream_id = s.id
		WHERE s.next_offset > 0
		AND (
			h.stream_id IS NULL
			OR h.checkpoint_offset IS NULL
			OR h.checkpoint_offset < s.next_offset
		)`,
		handlerKey,
	)
}

func packTestEvent(t testing.TB, event dogma.Event) *envelopepb.Envelope {
	t.Helper()

	mt, ok := dogma.RegisteredMessageTypeOf(event)
	if !ok {
		t.Fatalf("%T is not a registered message type", event)
	}

	data, err := event.MarshalBinary()
	if err != nil {
		t.Fatalf("unable to marshal %T: %v", event, err)
	}

	id := uuidpb.Generate()

	return envelopepb.NewEnvelopeBuilder().
		WithHeader(
			envelopepb.NewHeaderBuilder().
				WithCausationId(id).
				WithCorrelationId(id).
				WithSource(envelopepb.NewSourceBuilder().Build()).
				Build(),
		).
		WithBody(
			envelopepb.NewBodyBuilder().
				WithMessageId(id).
				WithCreatedAt(timestamppb.Now()).
				WithMessage(
					envelopepb.NewMessageBuilder().
						WithTypeId(uuidpb.MustParse(mt.ID())).
						WithDescription(event.MessageDescription()).
						WithData(data).
						Build(),
				).
				Build(),
		).
		Build()
}

// ExpectEqualEvents asserts that got and want contain the same events.
func ExpectEqualEvents(
	t testing.TB,
	description string,
	got []dogma.Event,
	want ...dogma.Event,
) {
	t.Helper()
	if !reflect.DeepEqual(got, want) {
		t.Logf("expectation failed: %s", description)
		t.Logf("+++ got:\n%s", dapper.Format(got))
		t.Logf("--- want:\n%s", dapper.Format(want))
		t.FailNow()
	}
}
