syntax = "proto3";
package runkit.poisonqueue.persistence.v1;

option go_package = "github.com/dogmatiq/runkit/internal/subsystem/poisonqueue/internal/persistence";

import "google/protobuf/timestamp.proto";
import "github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto";
import "github.com/dogmatiq/enginekit/protobuf/identitypb/identity.proto";

// QueueMessage is a message in the poison queue.
message QueueMessage {
  // CommandEnvelope is the envelope containing the command being enqueued.
  dogma.protobuf.Envelope command_envelope = 1;

  // FailedHandler is the identity of the handler that failed to process the
  // command.
  dogma.protobuf.Identity failed_handler = 2;

  // EnqueuedAt is the time at which the command was enqueued.
  google.protobuf.Timestamp enqueued_at = 3;
}
