// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: github.com/dogmatiq/runkit/internal/subsystem/poisonqueue/internal/persistence/message.proto

package persistence

import (
	envelopepb "github.com/dogmatiq/enginekit/protobuf/envelopepb"
	identitypb "github.com/dogmatiq/enginekit/protobuf/identitypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueMessage is a message in the poison queue.
type QueueMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CommandEnvelope is the envelope containing the command being enqueued.
	CommandEnvelope *envelopepb.Envelope `protobuf:"bytes,1,opt,name=command_envelope,json=commandEnvelope,proto3" json:"command_envelope,omitempty"`
	// FailedHandler is the identity of the handler that failed to process the
	// command.
	FailedHandler *identitypb.Identity `protobuf:"bytes,2,opt,name=failed_handler,json=failedHandler,proto3" json:"failed_handler,omitempty"`
	// EnqueuedAt is the time at which the command was enqueued.
	EnqueuedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMessage) GetCommandEnvelope() *envelopepb.Envelope {
	if x != nil {
		return x.CommandEnvelope
	}
	return nil
}

func (x *QueueMessage) GetFailedHandler() *identitypb.Identity {
	if x != nil {
		return x.FailedHandler
	}
	return nil
}

func (x *QueueMessage) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

var File_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDesc = "" +
	"\n" +
	"\\github.com/dogmatiq/runkit/internal/subsystem/poisonqueue/internal/persistence/message.proto\x12!runkit.poisonqueue.persistence.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a@github.com/dogmatiq/enginekit/protobuf/envelopepb/envelope.proto\x1a@github.com/dogmatiq/enginekit/protobuf/identitypb/identity.proto\"\xd1\x01\n" +
	"\fQueueMessage\x12C\n" +
	"\x10command_envelope\x18\x01 \x01(\v2\x18.dogma.protobuf.EnvelopeR\x0fcommandEnvelope\x12?\n" +
	"\x0efailed_handler\x18\x02 \x01(\v2\x18.dogma.protobuf.IdentityR\rfailedHandler\x12;\n" +
	"\venqueued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAtBPZNgithub.com/dogmatiq/runkit/internal/subsystem/poisonqueue/internal/persistenceb\x06proto3"

var (
	file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescData []byte
)

func file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDescData
}

var file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_goTypes = []any{
	(*QueueMessage)(nil),          // 0: runkit.poisonqueue.persistence.v1.QueueMessage
	(*envelopepb.Envelope)(nil),   // 1: dogma.protobuf.Envelope
	(*identitypb.Identity)(nil),   // 2: dogma.protobuf.Identity
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_depIdxs = []int32{
	1, // 0: runkit.poisonqueue.persistence.v1.QueueMessage.command_envelope:type_name -> dogma.protobuf.Envelope
	2, // 1: runkit.poisonqueue.persistence.v1.QueueMessage.failed_handler:type_name -> dogma.protobuf.Identity
	3, // 2: runkit.poisonqueue.persistence.v1.QueueMessage.enqueued_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_init()
}
func file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_init() {
	if File_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDesc), len(file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto = out.File
	file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_goTypes = nil
	file_github_com_dogmatiq_runkit_internal_subsystem_poisonqueue_internal_persistence_message_proto_depIdxs = nil
}
